apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: somesortademoorg/hellonode:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-node-svc
  labels:
    app: hello-node
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: hello-node
